/obj/effect/decal/cleanable/ants/attack_hand(mob/user, list/modifiers)
	. = ..()
	if(isanteater(user))
		to_chat(user, span_notice("You stick your snout in the anthill..."))
		if(!do_after(user, 2 SECONDS, target = src))
			return
		to_chat(user, span_notice("You slurp up all the ants you can find."))
		var/num_ants = reagents.get_reagent_amount(decal_reagent)
		reagents.trans_to(user, amount = num_ants, target_id = decal_reagent, methods = INGEST)
		qdel(src)
