directory = "_maps/map_files/TissStation/maintenance_modules/"

[rooms.engCentral]
modules = ["TEMPLATE-engCentral.dmm"]

[rooms.engUpperWest]
modules = ["TEMPLATE-engUpperWest.dmm"]

[rooms.mainCentralWest]
modules = ["TEMPLATE-mainCentralWest.dmm","mainCentralWest_1.dmm"]

[rooms.mainOuterWest]
modules = ["TEMPLATE-mainOuterWest.dmm"]

[rooms.medEast]
modules = ["TEMPLATE-medEast.dmm"]

[rooms.medMorgue]
modules = ["TEMPLATE-medMorgue.dmm","medMorgue_1.dmm"]

[rooms.medNorth]
modules = ["TEMPLATE-medNorth.dmm","medNorth_1.dmm"]

[rooms.medWest]
modules = ["TEMPLATE-medWest.dmm"]
