directory = "_maps/map_files/TissStation/maintenance_modules/"

[rooms.engCentral]
modules = ["engCentral_1.dmm"]

[rooms.engUpperWest]
modules = ["engUpperWest_1.dmm"]

[rooms.engUpperEast]
modules = ["engUpperEast_1.dmm"]

[rooms.mainCentralWest]
modules = ["mainCentralWest_1.dmm","mainCentralWest_2.dmm"]

[rooms.mainOuterWest]
modules = ["mainOuterWest_1.dmm"]

[rooms.mainOuterEast]
modules = ["mainOuterEast_1.dmm","mainOuterEast_2.dmm"]

[rooms.medEast]
modules = ["medEast_1.dmm","medEast_2.dmm"]

[rooms.medMorgue]
modules = ["medMorgue_1.dmm"]

[rooms.medNorth]
modules = ["medNorth_1.dmm"]

[rooms.medWest]
modules = ["medWest_1.dmm"]

[rooms.brig]
modules = ["brig_1.dmm", "brig_2.dmm"]
